// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class GuestEmail
{
    public int Id { get; set; }

    public string Email { get; set; }

    public DateTime CreatedAt { get; set; }
}