// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class Payment
{
    public int Id { get; set; }

    public decimal TotalAmount { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<SpotBooking> SpotBookings { get; set; } = new List<SpotBooking>();

    public virtual ICollection<TransferBooking> TransferBookings { get; set; } = new List<TransferBooking>();
}