// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class Spot
{
    public int Id { get; set; }

    public int DestinationId { get; set; }

    public int TourTypeId { get; set; }

    public string Duration { get; set; }

    public decimal AdultPrice { get; set; }

    public decimal ChildPrice { get; set; }

    public int Discount { get; set; }

    public virtual Destination Destination { get; set; }

    public virtual ICollection<SpotBooking> SpotBookings { get; set; } = new List<SpotBooking>();

    public virtual ICollection<SpotImage> SpotImages { get; set; } = new List<SpotImage>();

    public virtual ICollection<SpotLocalized> SpotLocalizeds { get; set; } = new List<SpotLocalized>();

    public virtual TourType TourType { get; set; }
}