// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class SpotImage
{
    public int Id { get; set; }

    public int SpotId { get; set; }

    public string ImgUrl { get; set; }

    public virtual Spot Spot { get; set; }
}