// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class TransferBooking
{
    public int Id { get; set; }

    public int PaymentId { get; set; }

    public string Destination { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string PickUpLocation { get; set; }

    public int Adults { get; set; }

    public int Children { get; set; }

    public DateOnly PickupDate { get; set; }

    public TimeOnly PickupTime { get; set; }

    public string SpecialRequest { get; set; }

    public virtual Payment Payment { get; set; }
}